'use strict';

const LAYERS = {
  request: {
    label: 'Request',
    detail: 'Judged before the route handler runs, from the shape of the request itself.',
  },
  abuse: {
    label: 'Abuse',
    detail: 'Volume rather than content. Refused in block mode whatever the severity says.',
  },
  runtime: {
    label: 'Runtime',
    detail: 'Raised from inside the handler, when request data reaches a dangerous call.',
  },
  response: {
    label: 'Response',
    detail: 'Judged on the way out, once the handler has decided what to send.',
  },
  baseline: {
    label: 'Baseline',
    detail: 'Deviation from what a route has been seen to receive. Never refuses unless learn.enforce is on.',
  },
};

const RULES = [
  {
    id: 'command',
    layer: 'runtime',
    severity: 'critical',
    sink: 'child_process',
    label: 'Shell command injection',
    detail:
      'Request data carrying shell metacharacters, or a null byte, reached exec, execSync or a spawn argument.',
    refuses: true,
  },
  {
    id: 'sql',
    layer: 'runtime',
    severity: 'critical',
    sink: 'database',
    label: 'SQL injection',
    detail:
      'Request data carrying SQL control characters was concatenated into a query handed to pg, mysql2 or better-sqlite3.',
    refuses: true,
  },
  {
    id: 'filesystem',
    layer: 'runtime',
    severity: 'critical',
    sink: 'fs',
    label: 'Path traversal',
    detail:
      'Request data supplying a parent-directory segment, an absolute path or a null byte reached a filesystem call.',
    refuses: true,
    note: 'Drops to high when the fragment is a traversal or an absolute path rather than a null byte.',
  },
  {
    id: 'ssrf',
    layer: 'runtime',
    severity: 'critical',
    sink: 'fetch',
    label: 'Server-side request forgery',
    detail:
      'Request data chose a non-HTTP scheme, or pointed an outbound fetch at a loopback, link-local or private address.',
    refuses: true,
    note: 'Critical for file:, gopher:, dict: and ftp:. High for an internal host over http.',
  },
  {
    id: 'prototype-pollution',
    layer: 'request',
    severity: 'critical',
    sink: 'request',
    label: 'Prototype pollution',
    detail:
      'A body, query or params key named __proto__, constructor or prototype, which can rewrite object prototypes.',
    refuses: true,
  },
  {
    id: 'nosql-operator',
    layer: 'request',
    severity: 'high',
    sink: 'request',
    label: 'NoSQL operator smuggling',
    detail:
      'A query operator such as $ne, $regex or $where arrived in a position that expected a plain value.',
    refuses: true,
  },
  {
    id: 'null-byte',
    layer: 'request',
    severity: 'high',
    sink: 'request',
    label: 'Null byte in a key',
    detail: 'A body, query or params key carries an embedded null byte.',
    refuses: true,
  },
  {
    id: 'payload-depth',
    layer: 'request',
    severity: 'medium',
    sink: 'request',
    label: 'Payload nests too deep',
    detail: 'The request nests deeper than the configured maxDepth, which defaults to 12 levels.',
    refuses: false,
  },
  {
    id: 'payload-size',
    layer: 'request',
    severity: 'medium',
    sink: 'request',
    label: 'Payload built to be expensive',
    detail:
      'More keys, longer strings or larger arrays than the configured ceilings — 300 keys, 64kB and 1000 items by default.',
    refuses: false,
  },
  {
    id: 'parameter-pollution',
    layer: 'request',
    severity: 'low',
    sink: 'request',
    label: 'Repeated query parameter',
    detail:
      'The same query parameter was supplied more than once, so it arrives as an array where the handler probably expects a string.',
    refuses: false,
  },
  {
    id: 'rate-limit',
    layer: 'abuse',
    severity: 'high',
    sink: 'rate-limit',
    label: 'Over the rate limit',
    detail: 'The client went past its allowance for that method and path within the window.',
    refuses: true,
    note: 'Drops to medium when the ceiling was lowered by event-loop shedding rather than by the client alone.',
  },
  {
    id: 'burst',
    layer: 'abuse',
    severity: 'high',
    sink: 'rate-limit',
    label: 'Burst',
    detail: 'Too many requests inside the burst window, which defaults to one second.',
    refuses: true,
  },
  {
    id: 'rate-block',
    layer: 'abuse',
    severity: 'high',
    sink: 'rate-limit',
    label: 'Temporarily blocked',
    detail:
      'The client is serving a block after repeatedly going over. Each strike doubles the wait, up to an hour.',
    refuses: true,
  },
  {
    id: 'concurrency',
    layer: 'abuse',
    severity: 'medium',
    sink: 'rate-limit',
    label: 'Too many requests in flight',
    detail: 'The client already has more requests open than the concurrency ceiling allows.',
    refuses: true,
  },
  {
    id: 'data-exposure',
    layer: 'response',
    severity: 'critical',
    sink: 'response',
    label: 'Secret or personal data in a response',
    detail:
      'A key or value in the JSON body looks like a credential, token or personal record on its way out.',
    refuses: true,
  },
  {
    id: 'xss',
    layer: 'response',
    severity: 'high',
    sink: 'response',
    label: 'Request data reflected as markup',
    detail: 'Something the caller sent came back inside an HTML response without being escaped.',
    refuses: true,
  },
  {
    id: 'open-redirect',
    layer: 'response',
    severity: 'high',
    sink: 'response',
    label: 'Redirect to a caller-supplied host',
    detail: 'The redirect target came from the request, so the caller chooses where the visitor lands.',
    refuses: true,
  },
  {
    id: 'insecure-cookie',
    layer: 'response',
    severity: 'high',
    sink: 'response',
    label: 'Cookie missing its flags',
    detail:
      'A Set-Cookie header went out without HttpOnly, Secure or SameSite. Shield rewrites the header rather than refusing the response.',
    refuses: false,
    note: 'Drops to medium when HttpOnly is present and only Secure or SameSite is missing.',
  },
  {
    id: 'unexpected-type',
    layer: 'baseline',
    severity: 'high',
    sink: 'request',
    label: 'Field arrived as the wrong type',
    detail: 'A field this route has always received as one type arrived as another.',
    refuses: false,
  },
  {
    id: 'unexpected-characters',
    layer: 'baseline',
    severity: 'high',
    sink: 'request',
    label: 'Field carries characters it never has',
    detail: 'The value uses a character class the learned profile has never seen in that field.',
    refuses: false,
    note: 'Drops to medium once the learned profile is already wide.',
  },
  {
    id: 'unexpected-field',
    layer: 'baseline',
    severity: 'medium',
    sink: 'request',
    label: 'Field never seen on this route',
    detail: 'A field arrived that the learned profile for this route has no record of.',
    refuses: false,
  },
  {
    id: 'unexpected-length',
    layer: 'baseline',
    severity: 'medium',
    sink: 'request',
    label: 'Field far longer than usual',
    detail: 'The value is well outside the length range learned for that field.',
    refuses: false,
  },
  {
    id: 'unexpected-value',
    layer: 'baseline',
    severity: 'medium',
    sink: 'request',
    label: 'Value outside the learned set',
    detail: 'A field that has only ever held a small fixed set of values arrived holding something else.',
    refuses: false,
  },
];

module.exports = { RULES, LAYERS };
