server {
    listen 80;
    listen [::]:80;
    server_name mta-sts.amitista.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://mta-sts.amitista.com$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name mta-sts.amitista.com;

    root /var/www/mta-sts;

    ssl_certificate     /etc/letsencrypt/live/amitista.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/amitista.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    access_log /var/log/nginx/mta-sts.access.log;
    error_log  /var/log/nginx/mta-sts.error.log;

    set $csp_style_hash "";

    include /etc/nginx/snippets/amitista-security-headers.conf;

    location ^~ /.well-known/ {
        include /etc/nginx/snippets/amitista-security-headers.conf;
        add_header Cache-Control "public, max-age=600" always;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 404;
    }

    location ~ /\. {
        return 404;
    }
}
