
add_header Access-Control-Allow-Origin  "*" always;
add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;

add_header Access-Control-Allow-Headers  "accept, authorization, if-none-match, if-modified-since" always;
add_header Access-Control-Expose-Headers "ETag, Last-Modified, Cache-Control, Retry-After" always;
add_header Access-Control-Max-Age        "86400" always;

if ($request_method = OPTIONS) {
    return 204;
}

limit_except GET HEAD {
    deny all;
}

error_page 403 =405 @api_405;
