limit_req zone=amitista_gateway burst=20 nodelay;

client_max_body_size 1k;
client_body_buffer_size 1k;

rewrite ^/api/v1(.*)$ /api/k/v1$1 break;

proxy_pass http://127.0.0.1:8789;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_connect_timeout 5s;
proxy_read_timeout 15s;

proxy_hide_header Cache-Control;
proxy_hide_header X-Powered-By;

error_page 502 504 =503 @api_unavailable;
