set $preload_links_home "</fonts/dm-sans-latin-normal.woff2>; rel=preload; as=font; type=font/woff2; crossorigin";
set $preload_links "</fonts/dm-sans-latin-normal.woff2>; rel=preload; as=font; type=font/woff2; crossorigin";
