[Definition]

actionstart =
actionstop  = /usr/local/sbin/amitista-nginx-ban.sh flush
actioncheck =
actionban   = /usr/local/sbin/amitista-nginx-ban.sh add <ip>
actionunban = /usr/local/sbin/amitista-nginx-ban.sh del <ip>
